### ISSUE TITLE
[一般]部署管理-应用运行监控界面，查询字段【资源中心】下的数据显示超出边界，建议调整界面布局。

### ISSUE THREAD

**Issue by xiexm** [AIPaaS/PaaS-FE-AMC-Inner#1]
[用户门户]部署管理-应用运行监控，查询字段资源中心下的数据显示超出边界，建议调整界面布局。
环境win7
浏览器：火狐
测试环境：
用户门户：http://10.1.245.247:16004/paas-web
[概要]：
[用户门户]部署管理-应用运行监控，查询字段资源中心下的数据显示超出边界，建议调整界面布局。
[详细步骤]：
部署管理-应用运行监控界面，查询字段【资源中心】下的数据显示超出边界，建议调整界面布局。
[实际结果]：
界面显示问题
[预期结果]:
界面显示正常
[重现率]:100%
[版本号]:

**Comment by Mcbingchuan** [comment]
已修改 请重新部署 wdep工程 部署成功后请清除浏览器缓存再刷新页面

**Comment by xiexm** [comment]
验证通过。

**Comment by xiexm** [comment]
验证通过。
