### ISSUE TITLE
[一般]同一个应用多次部署后，在应用运行监控列表界面同一个应用数据重复显示无法区别。

### ISSUE THREAD

**Issue by xiexm** [AIPaaS/PaaS-FE-AMC-Inner#2]
环境win7
浏览器：火狐
测试环境：
用户门户：http://10.1.245.247:16004/paas-web
[概要]：
同一个应用多次部署后，在应用运行监控列表界面同一个应用数据重复显示无法区别。
[详细步骤]：
1.[用户门户]部署管理-应用运行监控列表界面，同一个应用多次部署，在运行监控列表界面同一个应用数据显示一样，无法识别哪个是最后一次部署（预期结果：列表显示正在部署的实例）
[实际结果]：
同一个应用数据重复显示无法区别
[预期结果]:
列表显示正在部署的实例
[重现率]:100%

**Comment by Mcbingchuan** [comment]
已修改

**Comment by xiexm** [comment]
重复问题，暂时关闭，留一个。
