### ISSUE TITLE
[一般]部署管理-应用运行监控列表，A租户下用户user1，应用部署的实例，B租户下的用户登录后可以看到A的应用部署实例

### ISSUE THREAD

**Issue by xiexm** [AIPaaS/PaaS-FE-AMC-Inner#5]
环境win7
浏览器：火狐
测试环境：
用户门户：http://10.1.245.247:16004/paas-web
[概要]：[用户门户]部署管理-应用运行监控列表，A租户下用户user1，应用部署的实例，B租户下的用户登录后可以看到A的应用部署实例（数据权限问题）
[详细步骤]：
1.用户门户，部署管理-应用运行监控列表界面，A租户下用户user1登录，应用部署的实例，
2.B租户下用户登录后可以看到A的应用的部署实例。
[实际结果]：
数据显示权限问题
[预期结果]:
B租户下用户不应该看到A的应用的部署实例。
[重现率]:100%

**Comment by Mcbingchuan** [comment]
已修改

**Comment by xiexm** [comment]
验证通过
